# Generated by Django 4.1.4 on 2023-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
