# Generated by Django 4.1.4 on 2023-04-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rating_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='username',
            new_name='fullname',
        ),
    ]
